---
title: Classify T cells from multiple studies (human cancers)
author: "M. Andreatta <massimo.andreatta at unil.ch> and S. Carmona <santiago.carmona at unil.ch>"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
#output: html_notebook
---

```{r}
library(ggplot2)
library(Seurat)
library(UCell)
library(scGate)
#remotes::install_github("carmonalab/ProjecTILs", ref="26683f9")  #fix commit, for reproducibility
library(ProjecTILs)
library(SingleCellExperiment)
library(viridis)
```


We will use the collection of single-cell data by Zheng et al. (2021) Science, which covers 21 cancer types and 300 patients.

paper: https://www.science.org/doi/10.1126/science.abe6474
Data: https://zenodo.org/record/5461803#.YgT60GAo-eQ

```{r}
datapath <- "~/Dropbox/CSI/Datasets/Zhang_TIL_Science2021/data_CD8_sce_list.rds"

data.list <- readRDS(datapath)
names(data.list)
```

Convert to Seurat objects
```{r}
#For intial small tests
#data.list <- data.list[1:3]

tab <- ProjecTILs::Hs2Mm.convert.table

seurat.list <- lapply(X = names(data.list),  
                    FUN=function(x) {
                        mainExpName(data.list[[x]]) <- 'RNA'
                        
                        a <- names(assays(data.list[[x]]))
                        if ("counts" %in% a) {
                           counts.slot = "counts"
                        } else if ("log2TPM" %in% a) {
                           counts.slot = "log2TPM"
                        } else if ("norm_exprs" %in% a) {
                           counts.slot = "norm_exprs" 
                        }  
                        
                        #Use gene names for all objects (stored in display.name)
                        rownames(data.list[[x]]) <- rowData(data.list[[x]])[["display.name"]]  

                        r <- as.Seurat(data.list[[x]], counts = counts.slot, data = "norm_exprs", project=x)

                        r
                    })
names(seurat.list) <- names(data.list)
```

```{r}
saveRDS(seurat.list, "aux/Zheng.seurat.list.rds")
seurat.list <- readRDS("aux/Zheng.seurat.list.rds")
```

Some QC
```{r eval=F, fig.height=4}
t(as.data.frame(lapply(seurat.list, dim)))

seu.downsampled <- lapply(seurat.list,
                          FUN=function(x) {
                             Idents(x) <- "dataset"
                             subset(x, downsample=1000)
                          })

seurat.merged <- Reduce(merge, seu.downsampled)
Idents(seurat.merged) <- "dataset"
seurat.merged <- AddMetaData(seurat.merged, metadata = PercentageFeatureSet(seurat.merged, pattern = "^RP[LS]"), col.name = "percent.ribo")
seurat.merged <- AddMetaData(seurat.merged, metadata = PercentageFeatureSet(seurat.merged, pattern = "^MT-"), col.name = "percent.mito")

VlnPlot(seurat.merged, features = c("nFeature_RNA", "nCount_RNA","percent.ribo","percent.mito"), ncol = 2, pt.size=0)

VlnPlot(seurat.merged, features = c("LCK", "SPI1","MS4A1","LYZ","CD2","CD3E","CD3G","CD8A","NCAM1"), pt.size=0, stack = T, flip=T)
ggsave("plots/Zheng.sets.violins.png", height=8, width=15)
```


Check some signatures for major cell types
```{r}
sigs <- list("Immune"=c("PTPRC"),
             "Myeloid"=c("SPI1"),
             "Tcell"=c("CD3D","CD3E","CD3G","CD2"),
             "Cd8T"=c("CD8A","CD8B","CD4-"),
             "Cd4T"=c("CD4","CD40LG"),
             "Treg"=c("CD4","FOXP3"),
             "Stromal"= c("MMP2","COL1A1","COL1A2","COL5A1","LUM","PDGFRA"),
             "Bcell" = c("CD79A","MS4A1","BANK1","PAX5","CD19"),
             "NK" = c("KLRD1","NKG7","NCR1","FCGR3A","CD3D-","CD3E-","CD3G-"),
             "MoMacDC" = c("LYZ","CSF1R","MSR1","MAFB","CD300E"),
             "Plasma_cell" = c("IGKC","IGHG3","IGHG1","IGHA1","CD19-")
             )


cycling.g1 <- scGate::genes.blacklist.default$Hs$cellCycle.G1S
cycling.g2 <- scGate::genes.blacklist.default$Hs$cellCycle.G2M
cycling <- c(cycling.g1, cycling.g2)

sigs$cycling = cycling

seurat.list <- lapply(seurat.list,
       FUN = function(x) {
          AddModuleScore_UCell(x, features = sigs, name=NULL, ncores=4)
       })

```

```{r fig.height=6}

for (type in names(sigs)) {
  
  pll <- lapply(names(seurat.list),
                FUN = function(x) {
                  FeaturePlot(seurat.list[[x]], features=c(type), max.cutoff = 'q99') + 
   #                 scale_color_viridis(option="D", direction=1) + 
                    ggtitle(sprintf("%s (%s)", x, type))
                })
  
  wrap_plots(pll)
  ggsave(sprintf("plots/Zheng.sets.UCell.scores.%s.png", type), height=18, width=25)
}
```
Filter CD8 T cells
```{r}
models <- scGate::get_scGateDB()
cd8.model <- models$human$generic$CD8T

gated.list <- lapply(names(seurat.list),
       FUN = function(x) {
          print(sprintf("#Running dataset %s", x))
          scGate(seurat.list[[x]], model=cd8.model, ncores=4)
       })
names(gated.list) <- names(seurat.list)
```

Show results of gating per dataset
```{r fig.height=6}
cols = c("#10f87b","#fa765e")
names(cols) <- c("Pure","Impure")
pll <- lapply(names(gated.list),
       FUN = function(x) {
          DimPlot(gated.list[[x]], group.by="is.pure", cols = cols) + ggtitle(x)
       })

wrap_plots(pll)
ggsave("plots/Zheng.sets.gated.cd8t.png", height=18, width=25)

```
Convert to `sce`?
```{r}
gated.sce <- lapply(gated.list, function(x){
         as.SingleCellExperiment(x)
})

```

Save results of scGate
```{r}
saveRDS(gated.list, "aux/Zheng.seurat.gated.rds")
gated.list <- readRDS("aux/Zheng.seurat.gated.rds")
```


