---
title: Analyse proteasomal gene expression in Tex and T_EM
author: "M. Andreatta <massimo.andreatta at unil.ch> and S. Carmona <santiago.carmona at unil.ch>"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
#output: html_notebook
---

```{r}
library(ggplot2)
library(Seurat)
library(UCell)
library(scGate)
```



```{r}
signatures <- list(UPS = c("PSMB2", "PSMC3", "RBX1"),
                   PROTEASOME = c("PSMA1", "PSMA2", "PSMA3", "PSMA4", "PSMA5", "PSMA6", "PSMA7", "PSMB1", "PSMB2", "PSMB3", "PSMB4", "PSMB5", "PSMB6", "PSMB7", "PSMC1", "PSMC2", "PSMC3", "PSMC4", "PSMC5", "PSMC6", "PSMD1", "PSMD2", "PSMD3", "PSMD4", "PSMD6", "PSMD7", "PSMD8", "PSMD11", "PSMD12", "PSMD13", "PSMD14"),
                   HYPOXIC_EXHAUSTION  = c("PSMC3", "PSMB2", "RBPJ", "RBX1", "PKM", "PGK1", "PSMB8", "ENO1", "LDHA", "CHCHD2"),
                   HYPOXIC_EXHAUSTION_UNIQ = c("RBX1","PKM","PGK1","PSMB8","ENO1","LDHA","CHCHD2"),
                   CHAPERONES = c("PSMG1", "PSMG2", "PSMG3", "PSMG4", "POMP", "PSMD9", "PSMD5", "PAAF1"),
                   TF = c("NRF1", "NFE2L1"),
                   EXHAUSTION = c("HAVCR2","PDCD1","LAG3","TIGIT","TOX","ENTPD1","CTLA4"),
                   T_EX = c("HAVCR2","PDCD1","LAG3","TOX","TOX2","ENTPD1","CTLA4","CXCL13","GZMB"),
                   T_EM = c("IL7R","TCF7","GZMK","GZMM","ANXA1","CCL5"),
                   cellCycle.G1S = scGate::genes.blacklist.default$Hs$cellCycle.G1S,
                   cellCycle.G2M = scGate::genes.blacklist.default$Hs$cellCycle.G2M
                  )

```

Generated from "Generate_heatmap.Rmd"
```{r}

data_seurat <- readRDS("aux/Zheng.seurat.gated.annotated.Tex_Tem.merged.rds")

```

```{r}
data_seurat <- UCell::AddModuleScore_UCell(data_seurat,signatures,ncores = 4)
myFeaturesUcell <- paste0(names(signatures),"_UCell")
```

```{r}
VlnPlot(data_seurat,features = myFeaturesUcell, pt.size = 0, stack = T, flip = T)
ggsave("plots/signatures.vln.png", height=20, width=10)

```

```{r}
pp <- list()
pp[[1]] <- FeatureScatter(data_seurat,"EXHAUSTION_UCell","PROTEASOME_UCell", smooth = T, raster = T) + theme(aspect.ratio=1)
pp[[2]] <- FeatureScatter(data_seurat,"EXHAUSTION_UCell","HYPOXIC_EXHAUSTION_UNIQ_UCell", smooth = T, raster = T) + theme(aspect.ratio=1)
pp[[3]] <- FeatureScatter(data_seurat,"EXHAUSTION_UCell","CHAPERONES_UCell", smooth = T, raster = T) + theme(aspect.ratio=1)
pp[[4]] <- FeatureScatter(data_seurat,"PROTEASOME_UCell","HYPOXIC_UCell", smooth = T, raster = T) + theme(aspect.ratio=1)
wrap_plots(pp)
ggsave("plots/signatures.cor.png", height=10, width=10)
```



